const countries = [
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "gb", label: "United Kingdom" },
  { value: "au", label: "Australia" },
  { value: "de", label: "Germany" },
  { value: "fr", label: "France" },
  { value: "in", label: "India" },
  { value: "jp", label: "Japan" },
  { value: "cn", label: "China" },
  { value: "br", label: "Brazil" },
  { value: "za", label: "South Africa" },
  { value: "kr", label: "South Korea" },
  { value: "mx", label: "Mexico" },
  { value: "it", label: "Italy" },
  { value: "es", label: "Spain" },
  { value: "nl", label: "Netherlands" },
  { value: "se", label: "Sweden" },
  { value: "no", label: "Norway" },
  { value: "fi", label: "Finland" },
  { value: "dk", label: "Denmark" },
  { value: "ie", label: "Ireland" },
  { value: "pl", label: "Poland" },
  { value: "cz", label: "Czech Republic" },
  { value: "hu", label: "Hungary" },
  { value: "at", label: "Austria" },
  { value: "ch", label: "Switzerland" },
  { value: "ro", label: "Romania" },
  { value: "bg", label: "Bulgaria" },
  { value: "gr", label: "Greece" },
  { value: "tr", label: "Turkey" },
  { value: "il", label: "Israel" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "hk", label: "Hong Kong" },
  { value: "sg", label: "Singapore" },
  { value: "my", label: "Malaysia" },
  { value: "th", label: "Thailand" },
  { value: "ph", label: "Philippines" },
  { value: "vn", label: "Vietnam" },
  { value: "id", label: "Indonesia" },
  { value: "ng", label: "Nigeria" },
  { value: "ke", label: "Kenya" },
  { value: "ar", label: "Argentina" },
  { value: "cl", label: "Chile" },
  { value: "pe", label: "Peru" },
  { value: "co", label: "Colombia" },
  { value: "uy", label: "Uruguay" },
  { value: "bo", label: "Bolivia" },
  { value: "pa", label: "Panama" },
  { value: "do", label: "Dominican Republic" },
  { value: "ht", label: "Haiti" },
  { value: "jm", label: "Jamaica" },
  { value: "tt", label: "Trinidad and Tobago" },
  { value: "ws", label: "Samoa" },
  { value: "nz", label: "New Zealand" },
  { value: "fj", label: "Fiji" },
  { value: "tv", label: "Tuvalu" },
  { value: "pn", label: "Pitcairn Islands" },
  { value: "ck", label: "Cook Islands" },
  // Add more countries as needed
];

export default countries;
