// src/constants/countryCodes.js
const countryCodes = [
  { code: "+1", name: "USA" },
  { code: "+1_", name: "Canada" },
  { code: "+44", name: "UK" },
  { code: "+61", name: "Australia" },
  { code: "+49", name: "Germany" },
  { code: "+33", name: "France" },
  { code: "+34", name: "Spain" },
  { code: "+39", name: "Italy" },
  { code: "+81", name: "Japan" },
  { code: "+91", name: "India" },
  { code: "+86", name: "China" },
  { code: "+55", name: "Brazil" },
  { code: "+27", name: "South Africa" },
  { code: "+82", name: "South Korea" },
  { code: "+66", name: "Thailand" },
  { code: "+63", name: "Philippines" },
  { code: "+60", name: "Malaysia" },
  { code: "+62", name: "Indonesia" },
  { code: "+965", name: "Kuwait" },
  { code: "+971", name: "UAE" },
  { code: "+20", name: "Egypt" },
  { code: "+358", name: "Finland" },
  { code: "+46", name: "Sweden" },
  { code: "+47", name: "Norway" },
  { code: "+41", name: "Switzerland" },
  { code: "+372", name: "Estonia" },
  { code: "+370", name: "Lithuania" },
  { code: "+371", name: "Latvia" },
  { code: "+351", name: "Portugal" },
  { code: "+353", name: "Ireland" },
  { code: "+354", name: "Iceland" },
  { code: "+386", name: "Slovenia" },
  { code: "+36", name: "Hungary" },
  { code: "+421", name: "Slovakia" },
  { code: "+387", name: "Bosnia and Herzegovina" },
  { code: "+43", name: "Austria" },
  { code: "+375", name: "Belarus" },
  // Add more country codes as needed
];

export default countryCodes;
